### ISSUE TITLE
on Raspberry Pi 4

### ISSUE THREAD

**Issue by roehricht** [decke/drmdecrypt#1]
Try to make it on RPi 4 (Raspbian buster): "make" failed (unrec. com line option '-maes'). 
Would it be possible to transmit necessary changes for a RPi-Makefile?

**Comment by decke** [comment]
I've added more architectures and platforms to the CI setup and also made some improvements to the Makefile to build fine on all of them.

**Comment by roehricht** [comment]
Thanx a lot, Bernhard!
1. drmdecrypt Makefile runs fine on Raspbian buster (without AES-NI) and 
2. the made binary was also running (like a rabbit) with Samsung files: 
   a) mdb key was read, orig. file length ok, 
   b) no error in any (debug) output, 
   c) but TS output file only contains about a quarter to a third of original video length (and content) 
3. output file is okay, not corrupted, well playable, but to short

Anyway! 
Danke für die prompte Erledigung und die Mühen! 
Thank for working so hard and so well!
Wieland JC

**Comment by decke** [comment]
Could you tell me the exact length of the original file and the resulting output? Could be the 4GB limit or some other datatype issue.

**Comment by roehricht** [comment]
Thanx Bernhard, for reopening the issue!
Original files are between 1.3 and 1.48 GiB (about 43min film), I let run drmdecrypt ON raspian files and from raspian with files on other filesystems (on sticks: exFAT, FAT), on original Samsung formatted xfs stick with the originally TV captured files too: in every case nearly bit-exact the same result: about 460,5 to 878,7 MiB ts files with only 13min to 28min video length. I did not remove any file nor added something else.
Sincerely
Wieland JC
