### ISSUE TITLE
how can i decrypt my files?

### ISSUE THREAD

**Issue by leolpsdol** [decke/drmdecrypt#11]
I already have the recording files on my External HD and I already have drmdecrypt downloaded, but I don't know how to proceed to decrypt the files. Do I have to paste the files in some specific folder of those that I downloaded from this drmdecrypt?

My TV Model: Samsung UN49KU6400G

**Comment by decke** [comment]
Your model is not supported anyway. This only works for Series C / D and limited on E / F / H.
