### ISSUE TITLE
Available codecs cannot read output file

### ISSUE THREAD

**Issue by dhombios** [decke/drmdecrypt#3]
The available MPEG-TS codecs in Ubuntu and Windows cannot open the generated output files from recordings made in a 2011 Samsung smart tv.  Is it necessary to use a particular program for viewing them after being decrypted?

**Comment by decke** [comment]
Most likely the decryption silently failed for some reason in this case. What you usually get is a full MPEG2 stream which I usually played with vlc or mplayer.

**Comment by dhombios** [comment]
Thanks. I've been trying to find what is making the decryption process fail, but apparently it ends correctly (or at least it silently fails even if I run it in debugging mode):

```
./drmdecrypt -d  20141025143806.srf
INFO AES-NI CPU support disabled
INFO drm key successfully read from 20141025143806.mdb
INFO KEY: 00 00 00 00 00 00 00 00 00 54 3B 5C 00 00 00 00 
INFO Writing to ./20141025143806.ts
INFO Filesize 3004280832
INFO synced at offset 0
```

**Comment by peter99330** [comment]
Hey,

I have the exact same issue. The .ts file is generated and has the same size as the .srf file, but upon opening it with VLC nothing happens (the playlist shows a duration of 00:00). Any idea what might be wrong?

Thanks in advance!

**Comment by decke** [comment]
Most likely you have an Samsung TV from a later series (E or F) where they do not write the decryption key in the metadata file anymore. So the result is garbage and for sure cannot be played.

**Comment by peter99330** [comment]
Hey, thanks for the reply. That is the problem then. I did not check the TV model because I thought if the .mdb is present it will work.

I suppose this issues can be closed.
