### ISSUE TITLE
here: output = input - I found prof97/drmdecrypt to work for me

### ISSUE THREAD

**Issue by fowosu** [decke/drmdecrypt#5]
linux Mint 19.2 (32bit) and 20.1.(64bit) 
Samsung UE40D5700
Unfortunately I spent some hours with this code. 
Compiling works. DRM key is generated correctly.
However output file was/is identical to input file. 
I found prof79/drmdecrypt 
Can't tell were the original code came from but  prof97 worked perfectly for me.

**Comment by decke** [comment]
The code in prof79/drmdecrypt is a fork from this repository from 2014. So it is very close to drmdecrypt 1.0.

The best way to debug your problem is if you can provide the encrypted files from a short ~10sec recording.

**Comment by fowosu** [comment]
please let me know if you have received my private mail. don't want to upload anything here.

**Comment by decke** [comment]
Sorry, but I never received that recording. Could you please send it again and/or upload somewhere?

**Comment by decke** [comment]
I have now made a testsuite for drmdecrypt and added my own recordings from an UE40C6820 for 14 channels. Feel free to test yourself with a simple "make test" (needs libav installed) and also check the png files to verify that it worked fine.

**Comment by decke** [comment]
Looks good now.

Is it okay for you if i add your recording sample to the testsuite? It does not contain any sensitive data.

**Comment by fowosu** [comment]
Sure. put it into the test suite!
Suggestion:
Could you delete some srf files? One test srf for each TV type should be enough, don't you think?
Downloading 130mb doesn't really make sense. 
I guess decrypting is independent of the channel you record.

I have a srf files from a Samsung UE40F6340SS_XZG, but have not yet downloaded the drmkey. So I will get back to you if your code works for F series or not.

Anyway - great job. Thanks a lot!

**Comment by decke** [comment]
There are at least differences that depend on the source (DVB-S/T/C), scrambling info and where the payload begins (adaptation field). Since we are not using any parser that understands MPEG-TS packet format this is extremely simplified and thus fragile. I am quite sure there are more combinations which are still broken so extending the testsuite with more material is definitely the best way forward.

**Comment by fowosu** [comment]
Ok. Did not know this. 
My TV is connected via DVB-S.

**Comment by JoeBonziXP** [comment]
i have the same problem, should i send the file? it's a dvb-t recording, free channel, mdb file is in the folder
INFO KEY: 00 00 00 00 00 00 00 00 00 01 FD 00 00 00 00 00

**Comment by decke** [comment]
> i have the same problem, should i send the file? it's a dvb-t recording, free channel, mdb file is in the folder
> INFO KEY: 00 00 00 00 00 00 00 00 00 01 FD 00 00 00 00 00

This looks like an invalid key so could you please tell me from which Samsung model this is?

**Comment by JoeBonziXP** [comment]
UE46F5300 Software Version: T-MST12DEUC-2126.0

**Comment by decke** [comment]
This is a series F which is not supported because Samsung has moved the encryption key to internal storage.

**Comment by fowosu** [comment]
This issue was opened for UE40D5700 and it was solved by decke. Thanks again.
For my UE40F6340SS_XZG i did not find an easy way to get the key. 
So I stopped looking for it.

**Comment by JoeBonziXP** [comment]
should i make a new issue? or it's impossible to decrypt for my model?

**Comment by JoeBonziXP** [comment]
i have a series D5000 too but pvr is disabled, is there some software hack i can do?
