### ISSUE TITLE
Corrupted / unplayable output for C model

### ISSUE THREAD

**Issue by VADemon** [decke/drmdecrypt#6]
TV: UE40C6800US
Decrypted under Ubuntu 14.04 (LiveCD) + AES-NI
DRMDecrypt download: http://forum.samygo.tv/download/file.php?id=4253

The resulting .ts file is completely unplayable or corrupted, whereas decoding with SamyGO DRMDecrypt_Win64 works for me.

Files (ask me to reupload if I decide to delete them in the future):
Input files:
https://dl.dropbox.com/u/53753604/web/uploads/github/decke__drmdecrypt/20140508160013.ckf
https://dl.dropbox.com/u/53753604/web/uploads/github/decke__drmdecrypt/20140508160013.inf
https://dl.dropbox.com/u/53753604/web/uploads/github/decke__drmdecrypt/20140508160013.mdb
https://dl.dropbox.com/u/53753604/web/uploads/github/decke__drmdecrypt/20140508160013.mta
https://dl.dropbox.com/u/53753604/web/uploads/github/decke__drmdecrypt/20140508160013.srf

Output by decke/drmdecrypt (invalid):
https://dl.dropbox.com/u/53753604/web/uploads/github/decke__drmdecrypt/20140508160013-n_tv_-_Nachrichten.ts

Output by SamyGO DRMdecrypt (valid):
https://dl.dropbox.com/u/53753604/web/uploads/github/decke__drmdecrypt/outputbySamyGo_drmdecryptx64_20140508160013.ts

**Comment by decke** [comment]
Could you please try the following patch?

https://github.com/decke/drmdecrypt/pull/5/files

**Comment by VADemon** [comment]
```
./drmdecrypt -d -o ~/Downloads/ /media/it/HDD/TV/decodedonLinux/20140508160013.srf 

INFO AES-NI CPU support enabled
INFO drm key successfully read from 20140508160013.mdb
INFO KEY: 34 1D 9D DE 82 11 40 DA 65 32 0A 77 C5 6A D2 8C 
INFO Writing to /home/it/Downloads/20140508160013-n_tv_-_Nachrichten.ts
INFO Filesize 71614464
INFO synced at offset 0
WARN lost sync at 71437180
```
Using this pull request version: It worked!
